# Generated by Django 2.2.6 on 2019-11-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('discription', models.TextField()),
                ('visual', models.ImageField(blank=True, null=True, upload_to='project/images')),
                ('reference', models.TextField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('name', models.CharField(blank=True, max_length=48, null=True)),
            ],
        ),
    ]
