# Generated by Django 2.2.6 on 2019-11-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_auto_20191031_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='discription',
            new_name='description',
        ),
        migrations.AddField(
            model_name='bug',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bug',
            name='summary',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='bug',
            name='issue',
            field=models.CharField(max_length=256),
        ),
    ]
