# Generated by Django 2.2.6 on 2019-11-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_remove_bug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
