# Generated by Django 2.2.6 on 2019-11-15 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0005_auto_20191115_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='summary',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
