# Generated by Django 2.2.6 on 2019-11-15 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0006_auto_20191115_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
